# Generated by Django 5.0.7 on 2024-07-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_IRIXFQA.jpg', upload_to='profile_pics'),
        ),
    ]
